const express = require("express");
const router = express.Router();
const { verifyToken, restrictTo } = require("../middlewares/authMiddleware");
const { createAssignment, getAssignments, updateAssignment, deleteAssignment } = require("../controllers/assignmentController");
const { submitAssignment, getSubmissionsForAssignment, getMySubmissions } = require("../controllers/submissionController");
const { gradeSubmission } = require("../controllers/gradingController");
router.use(verifyToken);
router.route("/").post(restrictTo("Admin", "Mentor"), createAssignment).get(getAssignments);
router.route("/:id").put(restrictTo("Admin", "Mentor"), updateAssignment).delete(restrictTo("Admin", "Mentor"), deleteAssignment);
router.post("/submit", restrictTo("Student"), submitAssignment);
router.get("/my-submissions", restrictTo("Student"), getMySubmissions);
router.get("/:assignmentId/submissions", restrictTo("Admin", "Mentor"), getSubmissionsForAssignment);
router.patch("/submissions/:id/grade", restrictTo("Admin", "Mentor"), gradeSubmission);
module.exports = router;
