const express = require("express");
const router = express.Router();
const { markAttendance, getAttendanceHistory, getMentorStudents, getStudentAttendanceStats } = require("../controllers/attendanceController");
const { verifyToken, restrictTo } = require("../middlewares/authMiddleware");
router.use(verifyToken);
router.get("/students", restrictTo("Mentor", "Admin"), getMentorStudents);
router.get("/history", restrictTo("Mentor", "Admin", "Student"), getAttendanceHistory);
router.post("/attender", restrictTo("Mentor", "Admin"), markAttendance);
router.get("/stats/:studentId", restrictTo("Mentor", "Admin", "Student"), getStudentAttendanceStats);
module.exports = router;
